[package]
name = "ray-tracing-in-one-weekend"
version = "0.1.0"
edition = "2021" 

[dependencies]
winit = "0.28.3"
softbuffer = { version = "0.2.0" }
rand = "0.8.5"
rayon = "1.7.0"
glam = { version = "0.23.0", features = ["fast-math", "scalar-math"] }
